controller:
  buttons:
    manual_mode_select: 0
    default_camera_pos_select: 1
  axes:
    linear_speed_index: 4
    angular_speed_index: 0
    camera_x_index_: 6
    camera_y_index_: 7
  dead_zone: 3000
teleop:
  max_linear_speed: 4
  max_angular_speed: 4
motor:
  ramp:
    linear: 5.0
    angular: 5.0
